version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Building the artifact...
      - mvn compile --quiet
  build:
    commands:
      - echo Running tests
      - mvn test --quiet
      - echo Packaging application
      - mvn package docker:build -Dmaven.test.skip=true --quiet
      - docker tag kurtis/fifa-tournament:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image "$REPOSITORY_URI:$IMAGE_TAG"...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"fifa-tournament","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
cache:
  paths:
    - /var/lib/docker/**/*
artifacts:
  files: imagedefinitions.json